[tool.pytest.ini_options]
testpaths = ["back/tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "-v --tb=short"
pythonpath = [".", "back"]
asyncio_mode = "auto"
